spring:
  datasource:
    url: ${HALLOWEEN_DB_URL}
    username: ${HALLOWEEN_DB_USERNAME}
    password: ${HALLOWEEN_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        id:
          new_generator_mappings: false
    generate-ddl: false
springdoc:
  swagger-ui:
    tags-sorter: alpha
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

