spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update # for h2 sequence table
    show-sql: true
springdoc:
  swagger-ui:
    tags-sorter: alpha

