spring:
  datasource:
    url: jdbc:h2:file:./halloween_h2_db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop # for h2 sequence table
